server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
kafka:
  bootstrap-servers: localhost:9092
  topic: video_events
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
  consumer:
    group-id: video-events-consumer-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: earliest
