spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
server:
  port: 8080