server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
kafka:
  bootstrap-servers: localhost:9092
  topic: video_events
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
